Updated README.md
Solobrosco/monitor-bot pull request #8
Opened 2021-01-20 22:26 UTC by Solobrosco

2021-01-22 04:26 UTC, aaronvanoung requested changes
Definitely the format of the Readme is a lot better. One question I have is that when I use the install command I used npm, should we also add that as well ?

2021-01-22 10:14 UTC, Solobrosco commented
Really? I know npm is a manager for JavaScript while pip is a manager for python. Let's dispute this in the requirements issue where it deals with installation. This is just for the readme.md template.

2021-01-25 23:36 UTC, aaronvanoung commented
ohh i did not know that but yeah lets go with pip

2021-01-25 23:38 UTC, aaronvanoung approved these changes

2021-01-25 23:38 UTC, merged